source "https://rubygems.org"

gem 'activerecord' # ORM (object relational mapper)
gem 'sinatra-activerecord' # Rake tasks
gem 'rake' # Ability to automate some of our work
gem 'require_all' # Requires all gems
gem 'sqlite3' # Database
gem 'pry' # Debugging
