require_relative './config/environment'
require 'sinatra/activerecord/rake'

# rake -T
# rake --tasks


# rake <task_name>
# rake console
desc "Start our app console"
task :console do
  Pry.start
end
